version: '3.8'

services:
  backend:
    build: ./backend
    container_name: security_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env 
    restart: always
    volumes:
      - backend_data:/app 

  frontend:
    build: ./frontend
    container_name: security_frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
    restart: always

volumes:
  backend_data: