version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: security_db
    restart: always
    environment:
      POSTGRES_USER: nvrff
      POSTGRES_PASSWORD: nvrff
      POSTGRES_DB: securityhub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql_data

  backend:
    build: ./backend
    container_name: security_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env 
    depends_on:
      - db
    restart: always
    volumes:
      - backend_data:/app 

  frontend:
    build: ./frontend
    container_name: security_frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
    restart: always

volumes:
  backend_data:
  db_data:
