name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v3

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Устанавливаем зависимости
        working-directory: ./frontend
        run: npm install

      - name: Запускаем тесты React
        working-directory: ./frontend
        env:
          CI: true
        run: npm test

  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Устанавливаем зависимости и pytest
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Запускаем тесты Python
        working-directory: ./backend
        env:
          SECRET_KEY: "test_secret_key"
          DATABASE_URL: "postgresql://user:pass@localhost/db"
        run: pytest test_auth.py
